name: coffee_shop_app_mpp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  custom_navigation_bar: ^0.8.2
  connectivity_plus: ^6.1.3
  flutter_icons_null_safety: ^1.1.0
  provider: ^6.1.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  fl_chart: ^0.63.0
  http: ^1.2.2
  mime: ^1.0.6
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/

  fonts:
    - family: Food Zone
      fonts:
        - asset: fonts/foodzone.ttf
  
